### ISSUE TITLE
[Feature]: Better testing for Langfuse integration 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1075]
### The Feature

We've gotten several issues about our langfuse integration being broken over the last month. It would be helpful to have good testing around the following scenarios: 

## Proxy + Langfuse 
- Log /chat/completions, Log /chat/completions with stream 

## Package 
- Log acompletion, acompletion + stream, 
- Log completion, completion + stream 
- Log tool calling 

## Better testing 
Currently we just see if we any exceptions get raised. We NEED to check if langfuse actually flushes the response and it's available as a generation for all of the cases 

### Motivation, pitch

matters to our users

**Comment by ishaan-jaff** [comment]
imo it's insufficient to even check if langfuse sends a 200 or 201. I could see 201s and not see the generations on my langfuse account

**Comment by ishaan-jaff** [comment]
Here's a v1 attempt at this: we now read the status logs to verify all of them are 200/201

https://github.com/BerriAI/litellm/commit/b4c5bacea983aa2a424b0d6582a73588da0835c7

**Comment by ishaan-jaff** [comment]
- update this approach of reading debug logs from langfuse is failing on ci/cd

@marcklingen  @maxdeichmann It would be ideal if the langfuse package returns what gets logged by them and we can assert the LiteLLM I/O == the generation content logged by Langfuse

**Comment by maxdeichmann** [comment]
Hi @ishaan-jaff, in the latest SDK version we always return 207 as we send multiple events in one batch. The return body contains an `errors` array which contains errors per event. If there is an error, we log these with `warning`, so they should always be visible. 
On top of that, we return a `successes` array which contains a list of event ids alongside status codes per event. All of these are persisted in our db. Successes are only logged when debug mode is turned on.
Maybe you can upgrade and check for that?

**Comment by cwang** [comment]
Looking at the current source for Langfuse integration, it appears that `session_id` isn't picked by and later set via Langfuse's python SDK. I wonder if it was intentional (for some unknown reasons) or just not up to date per https://langfuse.com/docs/sessions ?

**Comment by bhaveshnarra** [comment]
@maxdeichmann can we get an update on @cwang 's question. Facing the same issue with LiteLLM and LangFuse integration

**Comment by cwang** [comment]
I think I worked it out in the end.

- The relationship between a trace and a session can be a *one-off* setup when a trace is created for a session. We usually do it by directly using Langfuse Python SDK at the beginning of a trace, i.e. setting `session_id` for the trace.
- As long as `trace_id` is set up and used throughout a trace, including using LiteLLM Langfuse integration, data will be recorded to the same trace, which is then aligned to the belonging session, i.e. no need for LiteLLM to do anything.
- The one little annoyance with LiteLLM Langfuse integration: because Langfuse trace follows an *upsert* approach whenever a trace is created, and the LiteLLM trace name is influenced by `generation_name` metadata, the end result would be that whichever is the *last* LiteLLM trace would decide the trace name ended up in Langfuse, which is never ideal. 
- The fix for the above point is to use Langfuse Python SDK to manually set the trace name back to the desirable value :( not ideal but works.

**Comment by bhaveshnarra** [comment]
Understood @cwang . thanks for clearing that up. Supporting langfuse's sessions on liteLLM via a metadata value seems like the right idiomatic approach. That way we would be able to use LiteLLM in proxy mode and still ingest the traces and sessions correctly

**Comment by maxdeichmann** [comment]
@cwang thanks for the explanation. I also think that generating the session yourself is the best approach here.

**Comment by ishaan-jaff** [comment]
@bhaveshnarra @cwang would this issue be solved if we let you pass a session id in your completion calls ? 

```python
response = completion(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "user", "content": "Hi 👋 - i'm openai"}
  ],
  metadata={
      "generation_name": "ishaan-test-generation",  # set langfuse Generation Name
      "generation_id": "gen-id22",                  # set langfuse Generation ID 
      "trace_id": "trace-id22",                     # set langfuse Trace ID
      "session_id": "session-id22",                     # set langfuse Session ID
      "trace_user_id": "user-id2",                  # set langfuse Trace User ID
  },
)
```

**Comment by cwang** [comment]
It's okay as it is because usually you'd need to set up Langfuse session and trace outside LiteLLM anyway, seeing that a LiteLLM completion is likely to be one part of a full trace. 

What I don't like is to use `generation_name` to update trace name, which is unnecessary and I'd argue wrong most of the time because trace name should ideally be decided outside LiteLLM as part of an LLM application's Langfuse tracing setup.

**Comment by bhaveshnarra** [comment]
@ishaan-jaff yes it would solve our issue
