### ISSUE TITLE
Streaming Error in Custom API Server(OpenAI format) with ChatLiteLLM: Missing LLM Provider

### ISSUE THREAD

**Issue by rahuldotar** [BerriAI/litellm#1120]
I'm facing an error when enabling streaming in the ChatLiteLLM setup for a Custom API Server. The error message is: "LLM Provider NOT provided."

`"ValueError(\"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/zephyr-7b-beta',..)` Learn more: https://docs.litellm.ai/docs/providers\")"`

**Steps to Reproduce**
Initialize ChatLiteLLM with streaming enabled.
Error occurs upon running.

Code Snippet
```

ChatLiteLLM(
    temperature=temperature,
    max_tokens=max_tokens,
    model="zephyr-7b-beta",
    streaming=streaming,
    verbose=True,
    callbacks=callbacks,
    api_base="http://0.0.0.0:8000/v1",
    custom_llm_provider="openai",
)
```
Additional Information
The issue seems related to the streaming feature.
A similar issue was resolved in the past after updating the system.

Environment Details
langchain==0.0.345
litellm==1.13.1

**Comment by ghost** [comment]
@rahuldotar can you try doing `model=openai/zephyr-7b-beta` and let me know if that works?

**Comment by ghost** [comment]
@rahuldotar following up on this. Was this issue resolved by making the change?

**Comment by Harryalways317** [comment]
Hi @krrishdholakia @rahuldotar   if you are still facing this, i have a quick fix but not a permanent one, but i'm trying to add that to main repo, for a quicke you can add this

https://github.com/Harryalways317/litellm/commit/efb4b761250dc69f3aa21fc86b11681f5b71838a

so, the issue comes because if the model is not there in openai if you mention openai/* then this occurs which is unlikely as per https://docs.litellm.ai/docs/providers/custom_openai_proxy

**Comment by rahuldotar** [comment]
Thanks, this issue was resolved. ❤️
