### ISSUE TITLE
[Bug]: Fix proxy open telemetry docs

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1159]
### What happened?

The docs mention you can send data to 3rd parties (not traceloop) but don't explain how 

<img width="1021" alt="Screenshot 2023-12-16 at 9 03 56 AM" src="https://github.com/BerriAI/litellm/assets/17561003/9ef32184-d09e-4570-a27a-94505fbc8ec6">

**Comment by ghost** [comment]
Context - user asked about this and i didn't how it worked. 

@ishaan-jaff having anything about this on docs would be really helpful.

**Comment by ishaan-jaff** [comment]
what were you confused about? The individual links tell you how to set traceloop configs

**Comment by ishaan-jaff** [comment]
also can you add more details here, what did the user ask for?

**Comment by ghost** [comment]
The user asked for how to set up dynamodb with the proxy. My first idea was to suggest the open telemetry integration. 

Here's a guide for doing that - https://medium.com/telemetryhub-dev/getting-observability-into-dynamodb-with-opentelemetry-in-node-288fb8537d46

But when I looked at the proxy docs, I couldn't figure out what configs I needed to tell them to set:

<img width="983" alt="Screenshot 2023-12-16 at 10 54 23 AM" src="https://github.com/BerriAI/litellm/assets/17561003/9ed0e4b2-e9f2-49b3-9993-91bd8625e475">


This says 'set Traceloop API key', but what is the name of the key in the environment? 

The user then asked ' but i don't want to send the data to traceloop' 

And i couldn't point them to how they could export the logs to a non-traceloop provider, even though it's mentioned in the docs - 

<img width="994" alt="Screenshot 2023-12-16 at 10 57 28 AM" src="https://github.com/BerriAI/litellm/assets/17561003/d61f1af4-51a5-4d80-a9b5-f34255e7dd7e">

--
The docs made me + the user think: 

1. The logs were being sent to traceloop
2. There was no way to modify the place it was being logged to 


It would be helpful if: 
1. The docs focused on 'openllmetry' and not traceloop (traceloop is the destination, openllmetry is the format unifier 
2. It was clear what the knobs to modify the destination were. 

I believe even openllmetry is inconsistent with how they do this. So 1 e2e example (maybe with the open telemetry collector - https://www.traceloop.com/docs/openllmetry/integrations/otel-collector) of: 
1. how to configure the destination 
2. what keys to set and what they're called

with links to the additional destinations on openllmetry docs would be sufficient. 

--
Update: I just realized your hyperlink on docs was to the openllmetry x dynatrace integration, and not to dynatrace's website itself. If that can be made more clear, it'd be awesome (i ignored it in the moment, because i assumed all the hyperlinks were just links to the websites of those providers)

**Comment by paneru-rajan** [comment]
I agree with @krrishdholakia on this, as it was confusing for me as well, took the initiative to make an improvement:

<img width="1179" alt="image" src="https://github.com/BerriAI/litellm/assets/4735661/61b1e345-d5a2-471a-b641-11c935959d42">

I've created the Pull-Request: https://github.com/BerriAI/litellm/pull/3445
