### ISSUE TITLE
[Bug]: Have gunicorn give request status logs

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1436]
### What happened?

This is super frustrating. The recent move to gunicorn meant that we lost the request status prints that unicorn used to do - 
<img width="1616" alt="Screenshot 2024-01-13 at 7 29 55 PM" src="https://github.com/BerriAI/litellm/assets/17561003/df0b1b67-2c35-4112-acd7-df1a173736ff">

My requests are hanging, but i can't even tell if the proxy received them

**Comment by ghost** [comment]
Turns out this is because the proxy is not running on port 8000. 

But this is **SUPER HARD** to tell. I currently parse through all the prints to find the port number (not fun). 
<img width="753" alt="Screenshot 2024-01-13 at 7 31 16 PM" src="https://github.com/BerriAI/litellm/assets/17561003/3624a5fe-d126-427e-9b9e-550ae47d07ce">

**Comment by ishaan-jaff** [comment]
we don't need to have gunicorn be the default way to startup the proxy, we can have users enable it with a flag `--gunicorn` 

I agree it was nice that uvicorn showed the request status logs

**Comment by ishaan-jaff** [comment]
added for gunicorn here https://github.com/BerriAI/litellm/commit/61dff3decbe898b5c9473333949e7f9a657e4ece 

ss of what logs look like - @krrishdholakia does this address your issue ? 
<img width="861" alt="Screenshot 2024-01-13 at 11 21 28 AM" src="https://github.com/BerriAI/litellm/assets/29436595/f68444d3-ae83-4140-aad4-e1522e8d9f83">

**Comment by ishaan-jaff** [comment]
closing since we do this now
