### ISSUE TITLE
Automated model list updater in docs?

### ISSUE THREAD

**Issue by zakhar-kogan** [BerriAI/litellm#147]
Just thought that some providers change their model list quite often (e.g. [Openrouter, heh](https://openrouter.ai/api/v1/models)), and two ideas came to mind:
- Some auto-action when compiling the docs ~~(complex)~~
- Just managing with the link to the provider...

**Comment by ghost** [comment]
this is a good idea - a v1 link to the provider sounds good. Feel free to make the relevant PR as well. 

Another thing is having good tutorials in our docs for each provider, so people know how to call them easily. 

I like @ishaan-jaff's together ai tutorial since it goes through streaming + non-streaming use-cases 

https://docs.litellm.ai/docs/tutorials/TogetherAI_liteLLM
