### ISSUE TITLE
[Bug]: Logging is skipped when cost tracking errors occur

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1768]
### What happened?

Related to https://github.com/BerriAI/litellm/issues/1767, since I noticed that there were no logs stored in S3 for requests that got this exception.

If we return _any_ response to the user/client, we should always log to places like the S3 bucket and/or Langfuse, even if there's an exception elsewhere IMO.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
@Manouchehri 

the error caused logs to fail because response cost is part of the logging object being sent to langfuse. 

If we try-except response cost in the logging object, this would mean even track_cost_callback (spend tracking is impacted) as it would fail silently 

What would you want to happen here?

**Comment by Manouchehri** [comment]
Hmm. Good point. I'll close this for now. :)
