### ISSUE TITLE
update team table schema for member roles

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2097]

**Comment by ghost** [comment]
Other impacted endpoints: 
- `/user/info` to return teams user is a member of -> currently we check if 'user_id' in the users column, but this won't work anymore since it'll be in a dictionary 


## Thinking 
- When team created, also update the `user` table with the new team that the user is a member of, and include the role the user has in that team 

Maybe a new column called `teams: String[]` 


```
teams: ["<team_id>",..]
```

**Comment by ghost** [comment]
this is now live
