### ISSUE TITLE
[Feature]: Azure AI Studio - Mistral Improvements

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2237]
### The Feature

> Why do we need to mention the api_base and api_key, which are not needed for the other models? It would be great if they are also read from the env variables.
> Thank you!

- Support env variables for Azure AI Mistral 
- Allow users to pass api_key as a completion param 
- Stop requiring /v1 for mistral azure ai studio

### Motivation, pitch

-

**Comment by santiagxf** [comment]
@ishaan-jaff, I still see the same errors happening on version `1.35.4`.

```python
import litellm._version
from litellm import completion

litellm._version.version
print("Current vesion", litellm._version.version)

litellm.set_verbose=True

response = completion(
    model="mistral/mistral-large", 
    api_base="https://[REDACTED].eastus2.inference.ai.azure.com",
    messages=[
       {"role": "user", "content": "hello from litellm"}
   ],
)
```

Output:

```bash
Current vesion 1.35.4


Request to litellm:
litellm.completion(model='mistral/mistral-large', api_base='https://[REDACTED].eastus2.inference.ai.azure.com/', messages=[{'role': 'user', 'content': 'hello from litellm'}])


self.optional_params: {}
kwargs[caching]: False; litellm.cache: None
Final returned optional params: {'extra_body': {}}
self.optional_params: {'extra_body': {}}


POST Request Sent from LiteLLM:
curl -X POST \
https://api.mistral.ai/v1/ \
-d '{'model': 'mistral-large', 'messages': [{'role': 'user', 'content': 'hello from litellm'}], 'extra_body': {}}'
```

I also tried using the `LiteLLM` and same error happens. Notice that `LiteLLM` looks a bit more appealing because otherwise you have to repeat all the time parameters `base_url` on each request.

One last comment, notice that `LiteLLM` uses parameter `base_url` for the URL, but `completions` uses `api_base` for that. It's a bit confusing.
