### ISSUE TITLE
Explicitly raise ContextWindowExceptions

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#228]
**Your feature request in one line**
Explicitly raise ContextWindowExceptions

**Describe the solution you'd like**
Raise an exception to specifically call out when a context window exceeded exception occurs. OpenAI can raise invalidrequest errors for several reasons - but the fallback strategy specifically for context window exceptions is different

**Comment by ghost** [comment]
cc: @yujonglee feel free to add any additional details

**Comment by yujonglee** [comment]
In the [OpenAI Docs](https://platform.openai.com/docs/guides/error-codes/python-library-error-types), it said `An InvalidRequestError indicates that your request was malformed or missing some required parameters, such as a token or an input. This could be due to a typo, a formatting error, or a logic error in your code.`

[And it can be `context_length_exceeded` too.](https://github.com/BerriAI/reliableGPT/blob/78d9e03123d42eac36959726448970346cf7bd17/build/lib/reliablegpt/IndividualRequest.py#L421-L422)

Like @krrishdholakia mentioned, one might want to retry with longer context window model only if `InvalidRequestError` is raised due to `context_length_exceeded`, and just raise exception for others(Since it is really invalid request).


It can be implemented as subclass of `openai.error.InvalidRequestError`.

**Comment by ghost** [comment]
Investigating this more - not all providers return a detailed enough error message (e.g. baseten returns a 500 error). We can implement this on a case-by-case basis (i.e. for those that do return a specific max tokens / context window exceeded message) we can return this exception (this should be the 90% case tbh).

**Comment by ghost** [comment]
added - https://docs.litellm.ai/docs/exception_mapping.

**Comment by ghost** [comment]
Should be available across all models from `v0.1.504` onwards
