### ISSUE TITLE
Adding new model through swagger

### ISSUE THREAD

**Issue by nlpravi** [BerriAI/litellm#2319]
Getting this error when trying to add a new model through /model/new 

{
  "error": {
    "message": "Authentication Error, 'model_list'",
    "type": "auth_error",
    "param": "None",
    "code": 400
  }
}

Here is my input

{
  "model_name": "azure-gpt-3.5",
  "litellm_params": {
       "model": "azure/xxxxx",
       "api_key": "xxxxx",
       "api_version": "2023-12-01-preview",
       "api_base": "https://xxxxx.openai.azure.com/"

   }
  
  }

**Comment by ghost** [comment]
@nlpravi i believe we're speaking this week? Let's debug this on call

If you can add the server logs to this ticket i can review beforehand as well

**Comment by ncecere** [comment]
any new update on this, I get the same error when trying to perform the same action via curl

**Comment by ghost** [comment]
Picking this up today

**Comment by ghost** [comment]
## Thinking 

- allow user to opt in to having model stored in db 
- treat local model storage as a cache - should check db after time period 
- persist model in db -> encrypt key

**Comment by ghost** [comment]
Will also need to make sure we just update model_list for router, not re-add all callbacks, etc. upon `/model/new` 

<img width="744" alt="Screenshot 2024-04-03 at 2 05 49 PM" src="https://github.com/BerriAI/litellm/assets/17561003/3adbe676-a299-4edb-b7e0-86658763384e">

**Comment by ghost** [comment]
Can use the master_key for encrypting/decrypting model api keys before storing in db

**Comment by ghost** [comment]
Hoping to have this fixed with https://github.com/BerriAI/litellm/pull/2827

Should enable persisting the model info to the db

- All litellm params (api key, base, etc.) are first encrypted using libsodium + your master key - https://libnacl.readthedocs.io/en/latest/
- Then encoded as a base64
- then stored to db 

For now, This is opt-in and only happens for models added via `/model/new`. 

```yaml
general_settings:
 store_model_in_db: true
```

Open to feedback on if you would expect this to persist it when calling `/model/new`

**Comment by ghost** [comment]
This is live now on v`1.34.26`.

**Comment by ushuz** [comment]
@krrishdholakia 

Storing models in DB makes a ton of sense. However, persisting API keys in DB may not be ideal, even encrypted.

> ... encrypted using libsodium + your master key ...

From an operation POV, what if the master key got rotated? The old master key won't be around to decrypt data from DB, when the new key is set, the encrypted data is virtually lost. Otherwise, a mechanism to decrypt/re-encrypt data on key rotation would be needed, either through the code or done by the operator, that's more coding/operational complexity.

From a security POV, DB could be backed up and exported for legitimate reasons. These DB copies would contain all the sensitive info, but may not always be handled with care. Even though the data inside is encrypted, it is still subject to attacks like brutal force. "You cannot leak what you don't have." Not persisting API keys would make one less attack surface.

**Comment by ghost** [comment]
Hey @ushuz great points.

Currently have this behind a feature flag - `store_model_in_db`, so we can work through these issues. 

Recapping issues: 

- using master key for decrypting can be problematic if you change the master key 
- storing keys in DB can lead to a new attack surface


For point 2: 

You can actually just pass in `os.environ/<env-name>` and that should work too. 

Here's a curl command i've been using to test the new endpoint, that works for me (also works if you pass in the same on ui): 

```bash
curl --location 'http://0.0.0.0:4000/model/new' \
--header 'Authorization: Bearer sk-1234' \
--header 'Content-Type: application/json' \
--data '{
  "model_name": "gpt-new",
  "litellm_params": {
     "model": "azure/chatgpt-v-2",
     "api_key": "os.environ/AZURE_API_KEY", # 👈 Not real key. Just env variable
     "api_base": "os.environ/AZURE_API_BASE",  # 👈 Not real key. Just env variable
     "api_version": "os.environ/AZURE_API_VERSION" # 👈 Not real key. Just env variable
  }
}'
```


For point 1: using master key for decrypting can be problematic

What's a better solution for this?

**Comment by ushuz** [comment]
> You can actually just pass in os.environ/<env-name> and that should work too.

@krrishdholakia - This is great and really helpful.

In that sense, I'm hoping to see more kinds of credentials could be set in this way, like:
```
azure.key-vault/<xxx>
aws.secrets-manager/<xxx>
gcp.secret-manager/<xxx>
gcp.cloud-kms/<xxx>
```

This could potentially eliminate any need to store API keys in DB.

And, it will solve point 1 as well. No sensitive data stored = No need for encryption.

---

But if the encryption has to stay, my thoughts:
- Only encrypt the sensitive part, the API keys, and leave non-sensitive bits in plaintext, this will make the data structure more flexible, and allow for fallback if the encrypted key becomes inaccessible
- Use a dedicated key for encryption, and set a certain entropy requirement to make sure it's a strong key
- Provide a mechanism to set the old & new encryption keys at the same time to re-encrypt the data on startup, to accommodate key rotation

**Comment by ghost** [comment]
Ok @ushuz, so we'd need to let a user

- generate an encrypted key
- add new models w/ their raw keys / any sensitive info (e.g. api base) encrypted and stored in db 
- rotate encrypted key

How do we store the encrypted key, so a user doesn't need to worry about remembering it each time they need to add a new model?

**Comment by ghost** [comment]
Thinking out loud:

- if a user opts in to persisting models on db
- store a hash of the master key in the db
- on startup - check if the current master key hash == the stored hash
- if not -> should we raise an error?

**Comment by ushuz** [comment]
@krrishdholakia - Just set the encryption key similar to how the master key is set, or any other key is set.

Encryption always comes with lots of complexity, so personally, I'd prefer we go this route and get rid of encryption. Any API key the user wants to use, put it in a proper secret store and reference it, or pass it in through envvar at startup.

> I'm hoping to see more kinds of credentials could be set in this way, like:
> ```
> azure.key-vault/<xxx>
> aws.secrets-manager/<xxx>
> gcp.secret-manager/<xxx>
> gcp.cloud-kms/<xxx>
> ```
