### ISSUE TITLE
Add context window size in contextwindowexception

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#265]
**Describe the solution you'd like**
Tell me the size of context window that the prompt failed for, so i know which model to rotate to. E.g. if it failed on claude-instant-1 (100k context window size) it doesn't make sense for me to try it on gpt-3.5-turbo. 

cc: @yujonglee for thoughts

**Comment by yujonglee** [comment]
@krrishdholakia I like the direction of this, but I think there is better way to do it.

My proposal: 

1. Keep [community-resource](https://github.com/BerriAI/litellm/blob/main/cookbook/community-resources/max_tokens.json) up-to-date, and make it more general. (ex, currently filename is `max_tokens`, but its top-level key is `MODEL_COST`.)  I also want this to have `provider`. Like `gpt3.5 - openai` info.

2. This should be single source of truth so that anyone can contribute and update fast. So https://github.com/BerriAI/litellm/blob/2dc1c35a05bdf45e7a466bdc1f6fd84658e58632/litellm/__init__.py#L38-L40 This should use [community-resource](https://github.com/BerriAI/litellm/blob/main/cookbook/community-resources/max_tokens.json), not hard-coded value.

3. Make helper function that takes model name as a input, and return max window size.

---

https://github.com/BerriAI/litellm/blob/2dc1c35a05bdf45e7a466bdc1f6fd84658e58632/litellm/exceptions.py#L32-L37

Now, since it already has `model` and `llm_provider`,  user can retrieve context window info and do whatever they want. In my use-case, I am doing fallback only to same type of model.

```python
# Part of my code
    LONGER_CONTEXT_MAPPING = {  # pragma: no cover
        "gpt-3.5-turbo": "gpt-3.5-turbo-16k",
        "gpt-3.5-turbo-0613": "gpt-3.5-turbo-16k-0613",
        "gpt-4": "gpt-4-32k",
        "gpt-4-0314": "gpt-4-32k-0314",
        "gpt-4-0613": "gpt-4-32k-0613",
    }
```

**Comment by ghost** [comment]
ok sounds good - i'll work on an implementation along these lines. We'll probably have to do something like get the community resource at initialization time, so it's not continuously making these HTTP calls.

**Comment by ghost** [comment]
Should be live in this - 73bb1b96e97a52b299c923f8b28b6eb296d3f15a / v0.1.526+
