### ISSUE TITLE
[Bug]: Proxy Team-based Langfuse logging not working

### ISSUE THREAD

**Issue by demux79** [BerriAI/litellm#2995]
### What happened?

Hello everyone! I love LiteLLM proxy, it's amazing.

We're excited to integrate Langfuse with the proxy using a teams configuration. It's been working great as a global logging solution so far.

Here’s what we've done:
1. We self-host our Langfuse server which is working great
2. We removed the global Langfuse configuration from LiteLLM proxy
3. We set up three teams, each with its own unique key
4. We added langfuse_host as an environment variable
5. We followed the setup instructions for config.yaml provided in the Langfuse integration documentation at the bottom of https://litellm.vercel.app/docs/proxy/team_based_routing

Unfortunately, we've hit a snag: no traces are appearing in Langfuse. The verbose logs show no entries about Langfuse. The llm calls work fine.

Could anyone shed some light on what might be going wrong? Any advice or suggestions would be greatly appreciated!

Thank you so much for your help!

**Comment by miga13** [comment]
Hello,

We have successfully implemented a workaround for the issue we encountered. The problem was twofold:

1. **Team ID Generation**: When creating a team via the UI, the system assigns a random UUID (e.g., 0812b59e-b80c-4301-80a9-f56fd18102e7). However, when creating a team through the following API call:
```
curl -X POST 'http://0.0.0.0:4000/key/generate' \
-H 'Authorization: Bearer MYGLOBALAPIKEY' \
-H 'Content-Type: application/json' \
-d '{"team_id": "production"}'
```
the _team_id_ is set to "production". This allows us to use this identifier in the config.yaml of LiteLLM Proxy.

2. **Configuration Issue** in LiteLLM-Proxy: We discovered an issue in the config.yaml of LiteLLM-Proxy. Changes made in the litellm_settings section were not being reflected in the LiteLLM-Proxy, even after recreating the Docker container. We resolved this issue by removing the related entries from PostgreSQL:
```
DELETE FROM "LiteLLM_Config" WHERE param_name = 'litellm_settings';
DELETE FROM "LiteLLM_Config" WHERE param_name = 'environment_variables';
```
Following these deletions and a restart of the docker container routing now operates seamlessly.
Thank you so much for LiteLLM Proxy.

**Comment by ishaan-jaff** [comment]
@miga13 @demux79 this is fixed here: https://github.com/BerriAI/litellm/pull/3039 + I also added testing for this issue

**Comment by ishaan-jaff** [comment]
@miga13 can we hop on a call sometime this week? I'd love to learn how we can improve litellm proxy for you 

If you can share your email here or on Linkedin - I can send over a meeting invite
Link to my calendly for your convenience - if you prefer to select any time: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-04

Link to my Linkedin if you want to dm me directly: https://www.linkedin.com/in/reffajnaahsi/

**Comment by ishaan-jaff** [comment]
closing since this is fixed
