### ISSUE TITLE
Update token counter to use more than tiktoken (coverage for anthropic, cohere, etc.) 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#312]
What's the problem? (if there are multiple - list as bullet points)
Improve `token_counter`. 

Even when a user is using litellm, they still need to go figure out client library stuff to get encodings / tokens. This should be fixed. 
<img width="754" alt="Screenshot 2023-09-09 at 7 16 18 PM" src="https://github.com/BerriAI/litellm/assets/17561003/c31782e0-aab9-45a1-8d10-87d3a090f2c1">

cc: @yujonglee thanks for surfacing this.

**Comment by ghost** [comment]
I think this is going to be a fairly large PR to do for all models / providers at once. It would make sense to me to break this down into smaller sections and tackle those individually.

**Comment by yujonglee** [comment]
For anyone interested - this code is part of `fastrepl`.

https://github.com/fastrepl/fastrepl/blob/7ef185e12b41d29aca869ea4440e5068a3344365/fastrepl/llm.py#L167-L181

**Comment by yujonglee** [comment]
OpenAI: https://github.com/openai/tiktoken
Cohere: https://docs.cohere.com/reference/tokenize
AI21: https://docs.ai21.com/reference/tokenize-ref
Others: https://huggingface.co/docs/transformers/model_doc/auto#transformers.AutoTokenizer

Note that for my use case in `fastrepl`, not a all models are needed since not all LLM provider exposes `logit_bias` option.

**Comment by ghost** [comment]
I believe anthropic has a local file we can use.

**Comment by ghost** [comment]
This is done
