### ISSUE TITLE
Improve error handling - if user submits a model name but didn't mention provider 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#314]
**Describe the solution you'd like**
![image](https://github.com/BerriAI/litellm/assets/17561003/8dcb858f-1727-4436-90b6-559601c7a496)

**Comment by ghost** [comment]
cc: @yujonglee 

it seems like your error got mapped but it's not clear to me which provider it assumed this was for (it should be together ai)

**Comment by yujonglee** [comment]
@krrishdholakia 
The problem here is that I use `togethercomputer/llama2`, but set `custom_llm_provider` to `openai`.

https://github.com/fastrepl/fastrepl/pull/102/commits/dd50361c87c4264167b10172fe99827787fbf2fe

I thought litellm can warn user if `custom_llm_provider` is used but `api_base` is not set.
But maybe there are other use-case of `custom_llm_provider` which does not need `api_base`?

**Comment by ghost** [comment]
@yujonglee in your case didn't you need the provider to be openai b/c you were using litellm as a proxy? 


I'm assuming you would need your server to then be able to determine if the model was for together ai?

**Comment by yujonglee** [comment]
@krrishdholakia

Yes you are right, but in this case I can also run the code in local. Proxy is used only in cloud runner.
So I conditionally change `custom_llm_provider` here. https://github.com/fastrepl/fastrepl/pull/102/commits/dd50361c87c4264167b10172fe99827787fbf2fe

**Comment by ishaan-jaff** [comment]
@krrishdholakia is this fixed ? I got a good error when i tried today
