### ISSUE TITLE
return mock responses for streaming 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#329]
What's the problem? (if there are multiple - list as bullet points)
`completion(.., mock_response=True)` works for normal completion, but breaks for streaming (needs to return a generator object with the text in the delta[content] chunk.

**Comment by ghost** [comment]
could potentially move this to a `mock_completion()` class. 

- pass in model, messages, stream flag
- return mock response 
- can also pass the string that gets returned instead of a flag and populate the token counts with the tokenizer. 


e.g.: `mock_completion(model, messages, stream, mock_response: str)`

**Comment by ghost** [comment]
done - cbc7e6dbc229b1c2985fcea2834891aa00051042, available in `v0.1.598` onwards.
