### ISSUE TITLE
[Bug]: vllm  'System prompt not supported' 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3325]
### What happened?

creating ticket to track @yaronr's issue on this 

> so I had to switch to /openai, but then it doesn't translate prompts correctly (for Gemma for example, I'm getting 'System prompt not supported'). Curious if you solved it.

### Twitter / LinkedIn details

cc: @yaronr @psykhi

**Comment by ghost** [comment]
noting the suggestion from previous issue: 

since vllm has a /v1/chat/completions endpoint, i thought they would naturally support/handle this. but it looks like i'm wrong here.

for hf models, we check if they support a system message, and if not we pass it in as a normal part of the prompt string (if it's a normal model) or a user message (if it's a chat/instruct model with a known prompt template) -

[litellm/litellm/llms/prompt_templates/factory.py](https://github.com/BerriAI/litellm/blob/4cccd470ab72cbc88d71204036229b39ccb8f44b/litellm/llms/prompt_templates/factory.py#L311)

Maybe we can expose a flag like `supports_system_message: bool`, and if it's set to false, we can pass it in as a user message. Thoughts? @yaronr

**Comment by yaronr** [comment]
@krrishdholakia That seems like the simplest thing that could possibly work :) and it would be great if you could support it.
Longer term, since this is model-related, maybe a more comprehensive solution would be to maintain this knowledge on a per-model level and do it automatically. Which would be aligned with the goals of litellm.

**Comment by ghost** [comment]
@yaronr yup - we do check this per model already with hf chat templates

I guess a 'neat' solution would be to apply the flag dynamically if the base model deployed on vllm doesn't support a system message
