### ISSUE TITLE
Add duration to budget manager (auto-reset user budget)

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#339]
**Describe the solution you'd like**
When a user budget is created, add a duration and maybe created at
```
budget_manager.create_budget(user=user, duration=monthly, created_at=time.time()) 
```

This will enable the budget to get auto-reset at the end of the billing period, instead of needing weird / custom logic to enable this.

**Comment by ghost** [comment]
cc: @yujonglee

**Comment by yujonglee** [comment]
At the first glance I thought providing single param like `reset_at`. 

But since 
1. monthly based will be most use-case
2. dealing with datatime need caution (might need things like http://labix.org/python-dateutil#head-ba5ffd4df8111d1b83fc194b97ebecf837add454)

it looks reasonable.

Would be more complete if this is tested/documented with scenarios like budget is updated during the month. (Upgrade)

**Comment by ghost** [comment]
Here's the test file - https://github.com/BerriAI/litellm/blob/main/litellm/tests/test_budget_manager.py

I'll think about a way to add this - open to PRs here as well

**Comment by ghost** [comment]
are you planning on keeping yours monthly @yujonglee

I was thinking of having duration be one of

['daily', 'weekly', 'monthly', 'yearly']

daily = 1d 
weekly = 7d
monthly = 28d 
yearly = 365d

**Comment by ghost** [comment]
This is one of those things that's a lot easier to implement hosted than via a package 😄 

E.g. in this case - running a cron job over the hosted db would probably be the simpler solution than trying to manage this on the server/pkg implementation

**Comment by ghost** [comment]
adding a way to do this locally - e1c91903da19532f595083c3b21343ecb355b63e, but this really doesn't feel like a proper solution (since somebody still needs to write a cron job to regularly check and update the user dict) 

I'll implement a cron job on the hosted endpoint, which should **actually** solve this problem

**Comment by ghost** [comment]
Just pushed the cron job. It'll basically runs 'update_budget_all_users' across the table every minute (can reduce the frequency if we end up if this becomes an issue).
