### ISSUE TITLE
[Feature]: Expose `/tokenize` endpoint -> return num tokens used for given input 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3680]
### The Feature

expose a `/tokenize` endpoint to count tokens for a given input 

- TGI exposes a `/tokenize` endpoint - https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/tokenize

- Aphrodite exposes a `/tokenize` endpoint - https://github.com/PygmalionAI/aphrodite-engine/blob/205c8e4106a9fc0cdc45102ea11b0eed80a807aa/aphrodite/endpoints/openai/api_server.py#L209

- OpenAI exposes token counting via tiktoken - https://github.com/openai/tiktoken

- Gemini exposes token counting via REST API - https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/get-token-count#gemini-get-token-count-samples-drest

### Motivation, pitch

help user avoid context window errors 

### Twitter / LinkedIn details

cc: @NiklasWilson

**Comment by thverney-dozo** [comment]
Hi,

I understand that the idea of exposing the /tokenize endpoint was previously abandoned due to concerns about its use for estimating costs with paid models. However, I’d like to suggest revisiting this feature.

The /tokenize endpoint is incredibly useful for scenarios such as:

Pre-checking input size to avoid context window errors.
Efficiently splitting large documents into manageable chunks for processing.

Other providers, like Hugging Face’s TGI, Gemini, and OpenAI’s tiktoken library, offer similar functionality, which has proven to be a valuable tool for developers and users.

Could you consider reintroducing this endpoint?

Thank you! 

An enthusiastic LiteLLM user.
