### ISSUE TITLE
[Feature]: Support Fine-Tuned VertexAI models 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#3821]
### The Feature

<img width="643" alt="Screenshot 2024-05-24 at 9 21 14 AM" src="https://github.com/BerriAI/litellm/assets/29436595/4c799a43-9e81-482e-9591-0229df8d7133">

### Motivation, pitch

-

**Comment by vivek-athina** [comment]
@ishaan-jaff Any update on this? We are also trying to use finetuned gemini models in our project but are blocked because of this.

**Comment by ishaan-jaff** [comment]
done here @vivek-athina https://github.com/BerriAI/litellm/pull/5371

**Comment by vivek-athina** [comment]
This PR is adding support for VertexAI and not Gemini. 
Gemini fine tuned models have more than a numerical id. For example ` tunedModels/ftgemini2-3sqcfb0762yx`
Please let us know once Gemini fine tuned models are supported or maybe add a link to that ticket so that we can try it once its implemented.
