### ISSUE TITLE
[Feature]: Return all responses when calling batch completion models 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#409]
### The Feature

as said above, when calling https://docs.litellm.ai/docs/completion/batching#send-1-completion-call-to-n-models

### Motivation, pitch

user feedback

**Comment by ishaan-jaff** [comment]
done: https://docs.litellm.ai/docs/completion/batching#send-1-completion-call-to-many-models-return-all-responses

**Comment by ghost** [comment]
nicely

**Comment by jamesleeht** [comment]
Hey @krrishdholakia sorry if this is not the right issue - this was the only issue I could find about batch completion.

Could I check why ThreadPoolExecutor is used here: https://github.com/BerriAI/litellm/blob/ef4c85522c001c930f02e2ec2c32dea9a7816b74/litellm/main.py#L2267-L2278

From my understanding, since most of the calls to the LLM servers will be API calls which seems to be a better fit for the `asyncio` library - please correct me if I'm wrong here.

**Comment by ghost** [comment]
Hey @jamesleeht we'd initially written this before a lot of our async work. 

Feel free to make a PR to move the function to use `litellm.acompletion()` instead! 

Any help here would be welcome
