### ISSUE TITLE
[Bug]: gpt-3.5-turbo-instruct not supported

### ISSUE THREAD

**Issue by StanGirard** [BerriAI/litellm#411]
### What happened?

Tried to use  gpt-3.5-turbo-instruct on Quivr

### Relevant log output

```shell
https://smith.langchain.com/public/7814d1a6-d387-4333-b893-35af5838d4ca/r
```

**Comment by ghost** [comment]
cc: @ishaan-jaff

**Comment by ghost** [comment]
@StanGirard acknowledging the bug, I'll pick this up and revert back with a fix in a few hours.

**Comment by ghost** [comment]
@StanGirard which version of litellm are you using. gpt-3.5-turbo-instruct was added a few days ago. If you could bump the version and let me know if that works, it'd be great! 

I think the issue is that the model list in the older version doesn't contain the instruct model name.

**Comment by ghost** [comment]
Sharing as proof. This works for me in 0.1.714

<img width="760" alt="Screenshot 2023-09-20 at 6 58 07 AM" src="https://github.com/BerriAI/litellm/assets/17561003/e8e4b112-093c-4a59-9172-c4d02e74267a">
<img width="625" alt="Screenshot 2023-09-20 at 6 58 25 AM" src="https://github.com/BerriAI/litellm/assets/17561003/422705df-a7ff-4b67-8d29-4ae39375180f">

**Comment by ghost** [comment]
As a potential improvement, we could decouple the model lists from the local package. This would make it easy to update lists and ensure everyone has the latest version. 

thoughts @ishaan-jaff / @StanGirard

**Comment by StanGirard** [comment]
I'm on litellm==0.1.531

That is probably why ;) 

Yeah that would be amazing to decouple it.

**Comment by StanGirard** [comment]
It works

**Comment by ghost** [comment]
Sounds good - I'll close this issue, and open a new one to track the decoupling idea.

**Comment by aleclarson** [comment]
In my PR for integrating LiteLLM with Aider, I'm updating the backup whenever the backup is older than 12 hours on Aider startup. If the backup is newer than 12 hours, I set the `LITELLM_LOCAL_MODEL_COST_MAP` to `True` (before importing LiteLLM) so the backup is used instead of hitting the network. I wonder if this approach should be merged into LiteLLM itself?

https://github.com/aleclarson/aider/blob/41ca019854a81cc49eb99135fc6977c0e0d03354/aider/main.py#L596-L629
