### ISSUE TITLE
[Feature]: Decouple model list from local package

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#412]
### The Feature

Move the model list to a hosted file (maybe read from the same model cost map file), so that we can easily add new models and not have it impact the actual package

### Motivation, pitch

Every time a new model is added (e.g. openai added gpt-3.5-instruct) the user needs to update their litellm package to access it. e.g. https://github.com/BerriAI/litellm/issues/411

**Comment by ghost** [comment]
Added: 
- [x] OpenAI 
- [x] Anthropic
- [x] Vertex AI 
- [x] AI21 
- [x] NLP Cloud 
- [x] Cohere 
- [x] Aleph Alpha
- [x] OpenRouter

to the model cost map

**Comment by ghost** [comment]
Next Steps: 
Instead of hardcoded names, get the model lists for the following providers from the model cost map: 
- open_ai_chat_completion_models
- open_ai_text_completion_models
- cohere_models
- anthropic_models
- openrouter_models
- vertex_chat_models
- vertex_code_chat_models
- vertex_text_models
- vertex_code_text_models
- ai21_models
- nlp_cloud_models
- aleph_alpha_models

**Comment by ghost** [comment]
Done from `v0.1.716` onwards. 


cc: @StanGirard @ishaan-jaff
