### ISSUE TITLE
Support for custom models imported in [Bedrock](https://docs.aws.amazon.com/bedrock/latest/userguide/model-customization-import-model.html).

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4239]
Support for custom models imported in [Bedrock](https://docs.aws.amazon.com/bedrock/latest/userguide/model-customization-import-model.html).

Use case: we have a fine-tuned model deployed in Bedrock. The tuned model is based on [OpenOrca](https://huggingface.co/Open-Orca/Mistral-7B-OpenOrca), so the start and end tokens are different than instruct version.

If the provider is `mistral`, the template uses the instruct template rather than OpenOrca's.

```
  response = client.invoke_model(
      body={"prompt": "<s>[INST] hello, tell me a joke [/INST]\n", "max_tokens": 1024, "temperature": 0},
      modelId=<model_id>,
      accept=accept,
      contentType=contentType
  )

```

Tokens`<|im_start|>` and `<|im_end|>` should be used instead.

Tried using a custom provider as a workaround. However, the body is empty and the request fails:

```
  response = client.invoke_model(
      body={},
      modelId=<model_id>,
      accept=accept,
      contentType=contentType
  )
```

The only thing we need is that prompt template configuration is respected, as it is done with `amazon` or `anthropic` providers.

```
      model_id: "model_arn"
      roles: {"system":{"pre_message":"<|im_start|>system\n", "post_message":"<|im_end|>"}, "assistant":{"pre_message":"<|im_start|>assistant\n","post_message":"<|im_end|>"}, "user":{"pre_message":"<|im_start|>user\n","post_message":"<|im_end|>"}}
      bos_token: "<s>"
      eos_token: "<|im_end|>"
```

https://github.com/BerriAI/litellm/blob/3a35a58859a145a4a568548316a1930340e7440a/litellm/llms/bedrock.py#L743-L746

_Originally posted by @andresd95 in https://github.com/BerriAI/litellm/issues/361#issuecomment-2172843397_

**Comment by manojmj92** [comment]
@krrishdholakia thank you for the work on this! I stumbled across this issue while I was trying to run imported models on Bedrock via litellm.

My trials failed, and I could not find any documentation around support for imported models on litellm. Are imported models fully supported by litellm? Is there an example I could look at?

**Comment by ghost** [comment]
hey @manojmj92 does something like this work? https://docs.litellm.ai/docs/providers/bedrock#provisioned-throughput-models

```
import litellm
response = litellm.completion(
    model="bedrock/anthropic.claude-instant-v1",
    model_id="provisioned-model-arn",
    messages=[{"content": "Hello, how are you?", "role": "user"}]
)
```

**Comment by manojmj92** [comment]
Thank you!

I'm wondering why we need to mention both model and model_id? Especially in
this example, anthropic Claude isn't something that I can import (because
it's closed source), and if my important model is mistral 7b, these params
aren't making much sense. What am I missing?

Regards,

Manoj M J

**Comment by manojmj92** [comment]
@krrishdholakia 

Thank you!

I'm wondering why we need to mention both `model` and `model_id`? Especially in
this example, anthropic Claude isn't something that I can import (because
it's closed source), and if my imported model is mistral 7b, these params
aren't making much sense. What am I missing? Are you meaning to say that no matter what I input in `model` (as long as it is any supported model), it does not have an effect if `model_id` is used? So it is essentially a kind of "hack" to get the code to work?

**Comment by davizucon** [comment]
Hello, 
Just for records, if anyone came here looking for how to use **imported** model like DeepSeek-R1-Distill-Llama-8B, in bedrock.

This is how I successfully invoked model:  
```
    import litellm
    response = litellm.completion(
        model="bedrock/meta.DeepSeek-R1-Distill-Llama-8B",
        model_id="provisioned-model-arn",
        messages=[{"content": "Hello, how are you?", "role": "user"}]
    )
```       
Looks like the _meta_ keywork  really matters in bedrock/chat/invoke_handler.py .

Best.

**Comment by ghost** [comment]
There's an open PR that fixes this @davizucon - https://github.com/BerriAI/litellm/pull/8132

can you test with release: https://pypi.org/project/litellm/1.59.10.dev1/

```python
response = completion(
                model="bedrock/llama/arn:aws:bedrock:us-east-1:086734376398:imported-model/r4c4kewx2s0n",  
                messages=[{"role": "user", "content": "Tell me a joke"}],
                client=client,
            )
```

from what we can tell it's the llama api spec, so we're following the pattern of `{provider}/{translation_spec}/model` 

- `bedrock/llama/arn:aws:bedrock:us-east-1:086734376398:imported-model/r4c4kewx2s0n`

let me know if this works @davizucon 

cc: @ishaan-jaff

**Comment by davizucon** [comment]
Hello @krrishdholakia , thanks for fast response!

Tested with same imported model in bedrock, using version 1.59.10.dev1 worked as expected !!!

just a slight change in boto3 client connection.

``` python
response = litellm.completion(
    model="bedrock/llama/arn:aws:bedrock:us-east-1:XXX:imported-model/XXXXX",
    messages=[{"role": "user", "content": "Tell me a joke"}],   
    aws_bedrock_client=bedrock_runtime
)
```

Thanks !
Best

**Comment by ghost** [comment]
@davizucon do you even need to set a client? i think it was a copy paste error on my part

**Comment by davizucon** [comment]
In my specific case, I think it depends on where I run this code. For a local test (request to AWS from my machine), I need to set it, because I have a strict security environment (and other things) . When running from the server, litellm as a proxy is not needed.

Correct me if I'm wrong. As far as I know, for this issue, this is not that relevant, just a detail.
