### ISSUE TITLE
[Feature]: min_p sampler support

### ISSUE THREAD

**Issue by FellowTraveler** [BerriAI/litellm#4822]
### The Feature

litellm appears to support top_p but fails to support min_p
This is a serious issue.

### Motivation, pitch

![image](https://github.com/user-attachments/assets/68993dbf-7351-4a09-8681-aeb6aca67191)
![image](https://github.com/user-attachments/assets/df00a03a-35db-4a48-ab5b-0da00cc15d6c)
![image](https://github.com/user-attachments/assets/ef256236-7160-442b-ae76-6e023106e6ba)

**Comment by ghost** [comment]
@FellowTraveler `min_p` doesn't look to be an openai param. 

If this is a provider specific param, it should be getting passed straight to the provider as a kwarg in the request body - https://docs.litellm.ai/docs/completion/provider_specific_params

Closing for now as covered by docs. If it doesn't work, can you reopen/create a new ticket with a sample script for repro + debug logs.

**Comment by BradKML** [comment]
Question (coming from an upstream issue https://github.com/All-Hands-AI/OpenHands/issues/5310):
1. Can `min_p` be hacked as a LiteLLM processor (since no provider is willing to carry it) for some of the non-compatible providers? Since there are many ways to take the information of `top_p` and re-sample them (e.g. 0.95 `top_p`=> input to 0.05 `min_p`)
2. How are these handled? Can they be integrated? Example providers https://github.com/ollama/ollama/issues/1142 https://openrouter.ai/docs/parameters#min-p
