### ISSUE TITLE
[Feature]: Build rate limit aware completion calls 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#521]
### The Feature

Here's how i think it should work: 
`litellm.completion(model, messages, max_rate_limit = 40000,)`

If you're within your rate limit it makes the call 

If you've crossed your rate limit it does not make the call. It cools down for 1min and then retries 

### Motivation, pitch

user request

**Comment by andersonbcdefg** [comment]
A couple notes on what would be useful here (I'm the person who requested this):
- Allow both tokens per minute and requests per minute as the rate limit (OAI often fails due to tokens, not requests)
- Allow user to specify multiple models & associated rate limits, and litellm will either split requests between them based on their rate limits, or fall back to model 2 when model 1 hits the limit, then model 3 when model 2 hits the limit, etc.

**Comment by ghost** [comment]
Thanks for this feedback @andersonbcdefg - this is really good feedback. Which models do you currently use (including for fallbacks) ?

**Comment by andersonbcdefg** [comment]
Usually just different OpenAI models! For instance it would be cool if 3.5 could fall back on 3.5-16k, which falls back on 4, which falls back on 4-32k (assuming that these all have independent rate limits, I forgot honestly). It would be even cooler to fall back across providers, but I don't (at present) use any providers besides OpenAI so that's not really a burning priority for me.

**Comment by ghost** [comment]
Does model fallbacks not solve this already? @andersonbcdefg 

https://docs.litellm.ai/docs/completion/reliable_completions#switch-modelsapi-keysapi-bases

**Comment by andersonbcdefg** [comment]
Hm... I feel like rate-limit-aware + fallbacks would look different. You could get a crude version of what I want by setting your rate limit too high and setting fallbacks, but the elegant think I'm imagining is, instead of "if model 1 fails, call model 2", it would look like "if at the limit for model 1, call model 2 until model 1 is ready again", or "call both model 1 and model 2 concurrently in a way that does not exceed either of their rate limits to get a higher overall effective rate limit".

**Comment by ghost** [comment]
@andersonbcdefg I believe ishaan took a stab at this for batch completion calls - https://docs.litellm.ai/docs/rate_limit_manager. 

Is this closer to what you're looking for?

**Comment by andersonbcdefg** [comment]
yeah this looks awesome!

**Comment by ishaan-jaff** [comment]
@andersonbcdefg I added rate limit aware acompletion calls:
basic logic:
- If it is in current capacity it makes the request 
- if over capacity then cooldown + retry for max retries 

https://docs.litellm.ai/docs/rate_limit_manager 

If possible can you try it and let me know how it can be better for you ?

**Comment by ishaan-jaff** [comment]
plan is to add fallbacks to this next

**Comment by ishaan-jaff** [comment]
usage:
```python
handler = RateLimitManager(
    max_requests_per_minute = 60,
    max_tokens_per_minute = 20000
)

response =  await handler.acompletion(
    model="gpt-3.5-turbo", 
    messages=[{
        "content": "Please provide a summary of the latest scientific discoveries."*10, 
        "role": "user"
    }]
)
```

**Comment by andersonbcdefg** [comment]
Yeah this is good, will keep an eye out for fallbacks

**Comment by ghost** [comment]
@andersonbcdefg was this what you were looking for? https://docs.litellm.ai/docs/routing#manage-multiple-deployments

please feel free to reopen the issue if not.
