### ISSUE TITLE
[Feature]: Hope to support the sglang AI inference engine

### ISSUE THREAD

**Issue by guleng** [BerriAI/litellm#5406]
### The Feature

Our previous model was encapsulated using VLLM, but after multiple tests and production applications, we found that SGLang is 3.8 times faster than VLLM. We hope Litellm can support it

### Motivation, pitch

![image](https://github.com/user-attachments/assets/3f5f47ba-72a7-4d38-aca9-54232f69de6b)

**Comment by ghost** [comment]
@guleng this is already supported

sglang is openai-compatible - https://github.com/sgl-project/sglang?tab=readme-ov-file#openai-compatible-api

Here's how to call it with litellm - https://docs.litellm.ai/docs/providers/openai_compatible

**Comment by guleng** [comment]
@krrishdholakia  @ishaan-jaff
 It's not like that, it's a C/S architecture, so I want to implement its client functionality on Litellm so that the client doesn't need to change and everything is processed at the gateway layer

The functionality on its client side：https://github.com/sgl-project/sglang/tree/main?tab=readme-ov-file#frontend-structured-generation-language-sglang

```
Flexible Frontend Language: Enables easy programming of LLM applications with chained generation calls, advanced prompting, control flow, multiple modalities, parallelism, and external interactions.
```

Can Litellm plan to add a feature?

**Comment by ghost** [comment]
@guleng if you want to use the client, just point it to the proxy as an openai model. the proxy is openai-compatible 
<img width="1108" alt="Screenshot 2024-09-02 at 6 44 21 AM" src="https://github.com/user-attachments/assets/48cca564-4691-4a79-a2f9-2d2faacdd7d6">

**Comment by guleng** [comment]
@krrishdholakia 
It supports the openai interface, which means the sglang client has additional features: with chained generation calls, advanced prompting, control flow, multiple modalities, parallelism, and external interactions.
I want to implement these features on Litellm so that customers don't have to make any code changes on the client side.
In this way, Litellm has both model acceleration function and model management authentication function.

**Comment by ghost** [comment]
> Litellm has both model acceleration function

I don't understand this. How would this be exposed to the user? 

---
You can add your custom model logic here - https://docs.litellm.ai/docs/providers/custom_llm_server

**Comment by guleng** [comment]
@krrishdholakia   Because sglang is faster than vllm, deploying models using sglang will have an acceleration effect. As long as the client functionality is implemented on litellm, I am not sure if using custom_1lm_Server can achieve this function. The example given is a bit vague.
thank you very much

**Comment by stevapple** [comment]
@krrishdholakia IIUC, SGLang has its own set of APIs alongside OpenAI-compatible ones. The native SRT (SGLang Runtime) APIs provide full capabilities like regex, JSON and token-level configuration support.

Since the native SGLang APIs doesn't support model selection, I don't think LiteLLM proxy is useful here. If we want to proxy SGLang backends, we may want general URL rewrite based on path prefix.

**Comment by ghost** [comment]
@stevapple 

Could you clarify what you mean re: model selection 

And 

"Path prefix" (is that like 'sglang/') ?

**Comment by stevapple** [comment]
> Could you clarify what you mean re: model selection 

In an OpenAI-compatible endpoint, we can use a `model` JSON parameter to distinguish different target models, so that different models can share the same endpoint. This is not a thing for native SGLang APIs (AFAIK), which doesn't have such mechanism and is only capable of inferencing a single model.

> "Path prefix" (is that like 'sglang/') ? 

Exactly. To really support SGLang (and any other provider-specific APIs) I would expect LiteLLM to perform URL rewrites like NGINX because there's not much else we can do.
