### ISSUE TITLE
[Bug]: user API keys are logged in verbose mode

### ISSUE THREAD

**Issue by toniengelhardt** [BerriAI/litellm#612]
### What happened?

When `set_verbose = True` LiteLLM logs user API keys to the output, which is really bad because they might end up unknowingly in log files.

Would recommend replacing chars with ***.

**Comment by ghost** [comment]
Hey @toniengelhardt, this is part of the verbose output to help debug what keys got used while making the api call (since you can pass in keys in multiple ways, switch models, etc.). 

I've found this to be really helpful when debugging my api calls. 

Why use verbose to output to log files vs. custom callbacks? https://docs.litellm.ai/docs/observability/custom_callback

**Comment by toniengelhardt** [comment]
Ah ok, got it. I've created a PR to add a warning to the docs to not use it in production (https://github.com/BerriAI/litellm/pull/625).

**Comment by ghost** [comment]
sounds good, closing issue as this is merged.
