### ISSUE TITLE
[Idea]: Add benchmarking against openai-python, anthropic, togetherai, google-generative-ai etc. SDKs 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#690]
### The Feature

Benchmark the performance of litellm against the python sdk's for provider libraries. Test for high-traffic scenarios (e.g. 100k requests / min.) and monkey-patch the actual request being made. 

This will help us monitor against bloat, and work on improving latency, etc. 

### Motivation, pitch

Increase confidence in using litellm for prod.

**Comment by ishaan-jaff** [comment]
we now do our 1k requests/second load tests and we benchmarked against openai

**Comment by ishaan-jaff** [comment]
Here's the perf of litellm proxy: https://docs.litellm.ai/docs/proxy/deploy#litellm-proxy-performance

**Comment by uripeled2** [comment]
The performance of LiteLLM is bad due to misuse of aiohttp client session. You should not create a session per request, you can find out more about it on the [aiohttp docs](https://docs.aiohttp.org/en/stable/client_quickstart.html)
In my opinion, the user should be able to set the client session from the acompletion function.

**Comment by ghost** [comment]
@uripeled2 if you're using the Router (recommended for high-traffic) we know the models you're requesting before hand, and create the clients (currently openai and azure) during init. 

This enables much better perf. 

Let me know if you have any specific providers you were trying to test against
