### ISSUE TITLE
[Bug]: Key Alias Validation

### ISSUE THREAD

**Issue by lokeish** [BerriAI/litellm#7373]
### What happened?

![image](https://github.com/user-attachments/assets/f9c905b2-f126-43ca-8eec-58448cfd5d9d)

1. When we try to create a key alias with the existing name, UI throws errors, so its completely fine.
2. when we try to do the same from API, it creates without any issues. 

What is the exact behavior? Key alias can be duplicate or unique?

### Relevant log output

```shell
NA
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.55.9

**Comment by ishaan-jaff** [comment]
can you share the api request @lokeish ? 

we should be enforcing it on the API too

**Comment by ghost** [comment]
Hi @lokeish this might be an older version. I can see this unique key alias is enforced on the backend server since v1.53.1 - https://github.com/BerriAI/litellm/blob/40e2a95095b9d8b39ed13d23b5234814acf7cf79/litellm/proxy/management_endpoints/key_management_endpoints.py#L1954

I also see this enforced via API - <img width="1139" alt="Screenshot 2024-12-27 at 10 29 56 AM" src="https://github.com/user-attachments/assets/4a71d52c-3097-46ce-836d-fc3d9db54c79" />
