### ISSUE TITLE
[Bug]: Error when running litellm_server with ollama: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by morgendigital** [BerriAI/litellm#757]
### What happened?

When trying to prompt the Chat Completion API with a local model that is served by ollama (e.g. ollama/mistral), I get the following HTTP error response:

```
{
    "detail": "'NoneType' object has no attribute 'get'\n\nTraceback (most recent call last):\n  File \"/app/litellm/litellm_server/main.py\", line 110, in chat_completion\n    server_settings.get(\"completion_model\", None) # server default\nAttributeError: 'NoneType' object has no attribute 'get'\n"
}
```

### Workaround
It works fine when system_settings.get() is commented out in `litellm_server/main.py` at line 110. Also, remove _"or"_ in line 111.

Original:
```
server_settings.get("completion_model", None) # server default
or model # model passed in url 
```

Edited:
```
# server_settings.get("completion_model", None) # server default
model # model passed in url 
```

### What else?
The error message suggests that there are no _server_settings_ present in the config file and I haven't found any documentation so far on how to add them. I attempted to add them based on the hint provided in the utils.py file:
```
server_settings:
  completion_model: mistral/ollama
```
...but that didn't work.

### Relevant log output

```
{
    "detail": "'NoneType' object has no attribute 'get'\n\nTraceback (most recent call last):\n  File \"/app/litellm/litellm_server/main.py\", line 110, in chat_completion\n    server_settings.get(\"completion_model\", None) # server default\nAttributeError: 'NoneType' object has no attribute 'get'\n"
}
```

### Twitter / LinkedIn details

https://www.linkedin.com/company/morgendigital

**Comment by ghost** [comment]
Hey @morgendigital can you run 
```
$ litellm --model ollama/mistral
```

and let me know if that works for you

**Comment by ghost** [comment]
bump on this @morgendigital

**Comment by morgendigital** [comment]
Hi @krrishdholakia, i haven't find the time to check it yet but will do it tomorrow and check in here - thank you for your help. I was trying to read through your code and run it manually first in order to understand and get to know it better, so I avoided just `pip install`ing and running it in the first place.

**Comment by JacobDu01** [comment]
I encountered the same problem and I want to use litellm_server as a proxy for requests from openai and together.ai. I did not configure any config.yaml or add the --model parameter, which can work normally in litellm. In order to use langfuse's trace capability, after switching to litellm_server, the same error message is prompted. Even after commenting out litellm_server/main.py#110, the logging logic still prompts an error at litellm/main.py#360.

**Comment by JacobDu** [comment]
I encountered the same problem and I want to use litellm_server as a proxy for requests from openai and together.ai. I did not configure any config.yaml or add the --model parameter, which can work normally in litellm. In order to use langfuse's trace capability, after switching to litellm_server, the same error message is prompted. Even after commenting out litellm_server/main.py#110, the logging logic still prompts an error at litellm/main.py#360.

**Comment by morgendigital** [comment]
Hi @krrishdholakia, I tried it and it runs fine if I launch it like this. Hmm.

**Comment by morgendigital** [comment]
> I encountered the same problem and I want to use litellm_server as a proxy for requests from openai and together.ai. I did not configure any config.yaml or add the --model parameter, which can work normally in litellm. In order to use langfuse's trace capability, after switching to litellm_server, the same error message is prompted. Even after commenting out litellm_server/main.py#110, the logging logic still prompts an error at litellm/main.py#360.

Hi @JacobDu, may I ask if you have also removed the "or" in line 111? Also, have you tried setting a config.yaml? Just use the example provided and enter your OpenAI details there. I just tested it and for me this fully works.

**Comment by ishaan-jaff** [comment]
Hi @morgendigital is this resolved for you?

**Comment by ishaan-jaff** [comment]
Hi @JacobDu I'd love to help with the error you're encountering - if you're open to it we can hop on a call and debug this together: 

sharing my cal for your convenience: 
https://calendly.com/ishaan-berri/30min

**Comment by JacobDu** [comment]
> > I encountered the same problem and I want to use litellm_server as a proxy for requests from openai and together.ai. I did not configure any config.yaml or add the --model parameter, which can work normally in litellm. In order to use langfuse's trace capability, after switching to litellm_server, the same error message is prompted. Even after commenting out litellm_server/main.py#110, the logging logic still prompts an error at litellm/main.py#360.
> 
> Hi @JacobDu, may I ask if you have also removed the "or" in line 111? Also, have you tried setting a config.yaml? Just use the example provided and enter your OpenAI details there. I just tested it and for me this fully works.

Hi @morgendigital, after modifying line 111, litellm_server can run normally. In addition, the logging issue was caused by my failure to install `langfuse` using pip. This problem has been resolved.

**Comment by clalanliu** [comment]
I use config.yaml to configure and launch litellm_server container. Also get the simililar issue. I guess this is because when we don't specify --model (because I use configure so I guess I don't need to do this), line 110 in main.py
`server_settings.get("completion_model", None) # server default`
will trigger the error.

I fix my problem by the following modification (line109):
```
data["model"] = (
            #server_settings.get("completion_model", None) # server default
            model # model passed in url 
            or data["model"] # default passed in
        )
```

**Comment by ishaan-jaff** [comment]
@clalanliu @morgendigital updated docs on using the config:
https://docs.litellm.ai/docs/simple_proxy#proxy-configs

**Comment by ishaan-jaff** [comment]
the very first model in the config will be the default - is this desired behavior for your use case ?

**Comment by ghost** [comment]
closing as i believe this is now fixed.
