### ISSUE TITLE
Remove anthropic package dependency

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#81]
They introduced breaking changes to their sdk. Seems like they're rapidly evolving it - this causes breaking changes to us in prod. Switch to making REST API calls.

**Comment by ghost** [comment]
<img width="1474" alt="Screenshot 2023-08-09 at 12 44 50 PM" src="https://github.com/BerriAI/litellm/assets/17561003/2adbc212-bc77-4a77-87c8-b2c5e096f03d">

this is causing me to fail requests in prod. 

Looks like the error is caused due to the version of pydantic I have on my server. 
    - I could reinstall the ‘right’ version of pydantic, but that seems weird, and I feel like I’ll encounter other similar problems to this. 
    - V0: move to just calling the anthropic REST endpoint and see if that helps solve the current issue.

**Comment by ghost** [comment]
ended up pausing on this because of streaming. 

To implement streaming via endpoints, we'd have to write our own version of this - https://github.com/anthropics/anthropic-sdk-python/blob/9db4b34844c5bfee65ab4e1ad448ae13d6469e5f/src/anthropic/_streaming.py#L4

We should do this sooner than later so we can start removing dependencies on external packages.

**Comment by ishaan-jaff** [comment]
done
