### ISSUE TITLE
[Feature]: Allow setting rate limits on virtual keys

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#931]
### The Feature

Would be helpful here - https://github.com/and-voila/labs/issues/210

### Motivation, pitch

help potential user

**Comment by ghost** [comment]
+1 more user: 

"if more than x api calls are made in parallel, our user should get either:
A.) some HTTP error (503, resource busy, or whatever)
B.) his request will be put in a batch and will be handled first-in-first-out when resources are free again. up to some point where some timout triggers maybe (but not needed)"

**Comment by ghost** [comment]
**Note:** usually you do rate limiting by tpm or tps (transactions per minute or second), which is not really what we want.

"pretty much exactly this, yes. im not sure if the user mentions what type of rate limits. there are multiple approachable possibilities here. mine is basically a rate limit based on x parallel requests, where x is some value stored in the database (together with key, expiry date, etc.)
if user's parallel requests > x, send a 503 error (or better: batch his request in some queue)
if user's parallel requests <= x, let him use the API freely.
because usually you do rate limiting by tpm or tps (transactions per minute or second), which is not really what we want. and i could technically solve it already with litellm as you allow to set such types of limits already"

**Comment by ghost** [comment]
Potential solution

```python
from fastapi import FastAPI, HTTPException, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from starlette.requests import Request
from some_redis_client_module import Redis  # this is pseudo code replace it with actual module

security = HTTPBearer()

app = FastAPI()
redis = Redis(host='localhost', port=6379, db=0)


@app.middleware("http")
async def rate_limit_per_token(request: Request, call_next):
    auth: HTTPAuthorizationCredentials = Depends(security)
    token = auth.credentials

    if not token:
        return call_next(request)

    # Decrease count for this token
    current = redis.get(token)
    if not current:
        redis.set(token, 1)
    elif int(current) >= MAX_PARALLEL_REQUESTS:  # Replace MAX_PARALLEL_REQUESTS with an integer limit
        raise HTTPException(status_code=429, detail="Too many requests.")

    # Increase count for this token
    redis.incr(token)

    response = await call_next(request)

    # Decrease count for this token
    redis.decr(token)

    return response


@app.get("/")
def read_root(token: HTTPAuthorizationCredentials = Depends(security)):
    return {"Hello": "World"}
```

**Comment by ghost** [comment]
initial solution (setting max parallel requests in config, and applying that / key), didn't solve the user issue. 

User wants to set it on key gen.

This is a prod blocker.

**Comment by ghost** [comment]
user suggested code: 
```shell
curl -X 'POST' \
  'https://my.apiurl.ai/key/generate' \
  -H 'accept: application/json' \
  -H 'Authorization: THE_MASTER_KEY_FROM_CONFIG_YAML' \
  -H 'Content-Type: application/json' \
  -d '{
  "duration": "30d",
  "models": [],
  "aliases": {},
  "config": {},
  "spend": 0,
  "user_id": "string",
  "max_parallel_requests": 5,
}'
```

**Comment by ghost** [comment]
Our current approach doesn't make sense in this context. If max parallel requests is stored in the db, then we should leverage `user_api_key_auth` to pull this information. Since this is already being done for `/chat/completions` and `/embeddings`, it might make more sense to use something like pre/post-call hooks https://github.com/BerriAI/litellm/issues/1037

Since those are instrumented to be inside chat completions / embeddings functions (so the api key has already been parsed, validated, etc.).

**Comment by ghost** [comment]
Initial commit with new approach pushed - https://github.com/BerriAI/litellm/commit/5fa2b6e5ad58fa6bea8b19b02169b394b7fa6011

Awaiting user feedback

cc: @morgendigital

**Comment by ghost** [comment]
closing as this works in prod v`1.12.1`.
